name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.0.4
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker login docker.pkg.github.com -u Hitsounds -p ${{ secrets.GITHUB_TOKEN }} |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7 \
            -t docker.pkg.github.com/hitsounds/discord-bot/latest:1.0.0 \
            --output "type=image,push=false" \
            --file ./Dockerfile . |
          docker push docker.pkg.github.com/hitsounds/discord-bot/latest:1.0.0
          
          
