name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker login docker.pkg.github.com -u hitsounds -p ${{ secrets.GITHUB_TOKEN }}
          docker buildx --platform linux/amd64,linux/arm64,linux/arm/v7 . --file Dockerfile -t docker.pkg.github.com/Hitsounds/discord-bot/dBot:latest
          docker push docker.pkg.github.com/Hitsounds/discord-bot/dBot:latest
          
          
